# Numpy Introduction

In [1]:
import numpy as np

### Array

In [2]:
a =np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
a = np.zeros(6)
a

array([0., 0., 0., 0., 0., 0.])

In [4]:
a = np.ones(6)
a

array([1., 1., 1., 1., 1., 1.])

In [5]:
print(np.arange(4))
print(np.arange(0,8,3))

[0 1 2 3]
[0 3 6]


### Add, Remove, Sort

In [7]:
ar = np.arange(8)
np.append(ar,[8,9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.delete(ar,[2,4,6])

array([0, 1, 3, 5, 7])

In [11]:
asc = np.sort(ar)
desc = np.sort(ar)[::-1]
print("ascending : " , asc)
print("descending : ", desc)

ascending :  [0 1 2 3 4 5 6 7]
descending :  [7 6 5 4 3 2 1 0]


### Shape and Size

In [12]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([1., 1., 1., 1., 1., 1.])

`.ndim` memberi tahu jumlah axes, atau dimensi dari array

In [13]:
arr.ndim

2

`.size` : jumlah total elemen array.

In [14]:
arr.size

12

`.shape`: menampilkan tuple integer yg menunjukkan jumlah elemen yang disimpan di setiap dimensi array. contoh 2 row dan 3 col, maka menjadi (2,3)

In [15]:
arr.shape

(3, 4)

### Reshape

beberapa parameter: 
`numpy.reshape(a, newshape,order)`

In [17]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7])

In [37]:
print()
print("before:\n",ar, "\nshape: ")
print("after:\n", ar.reshape(4,2))



before:
 [0 1 2 3 4 5 6 7] 
shape: 
after:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]


### Convert 1D to 2D
np.newaxis

In [38]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7])

In [63]:
ar.shape

(8,)

In [42]:
ar2 = ar[np.newaxis,:]
ar2

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [49]:
print(ar.ndim,"\n",
ar2.ndim)

1 
 2


In [50]:
ar2.shape

(1, 8)

np.expand_dims

In [53]:
arr

(3, 4)

In [54]:
arr.shape

(3, 4)

In [71]:
arr_ex = np.expand_dims(arr, axis=0)

In [72]:
arr_ex

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [73]:
arr_ex.shape

(1, 3, 4)

In [74]:
arr_ex[np.newaxis, :].shape

(1, 1, 3, 4)

### Indexing and Slicing
    arr[start:stop:step]

In [77]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7])

In [80]:
ar[4:]

array([4, 5, 6, 7])

In [85]:
ar[2:8:2]

array([2, 4, 6])

In [87]:
ar > 2   

array([False, False, False,  True,  True,  True,  True,  True])

In [88]:
ar[ar>2]

array([3, 4, 5, 6, 7])

In [89]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [93]:
arr>5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [94]:
arr%2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [95]:
arr[arr%3 == 0]

array([ 3,  6,  9, 12])

In [96]:
(arr % 2 == 0) & (arr % 3 == 0)

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False,  True]])

In [97]:
arr[(arr % 2 == 0) & (arr % 3 == 0)]

array([ 6, 12])

### Creating from Existing Data
- np.vstack()
- np.hstack() 
- np.vsplit()
- np.hsplit()
- .view()
- .copy()