# Numpy Introduction

In [1]:
import numpy as np

## Array

In [2]:
a =np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
a = np.zeros(6)
a

array([0., 0., 0., 0., 0., 0.])

In [4]:
a = np.ones(6)
a

array([1., 1., 1., 1., 1., 1.])

In [5]:
print(np.arange(4))
print(np.arange(0,8,3))

[0 1 2 3]
[0 3 6]


## Add, Remove, Sort

In [7]:
ar = np.arange(8)
np.append(ar,[8,9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.delete(ar,[2,4,6])

array([0, 1, 3, 5, 7])

In [11]:
asc = np.sort(ar)
desc = np.sort(ar)[::-1]
print("ascending : " , asc)
print("descending : ", desc)

ascending :  [0 1 2 3 4 5 6 7]
descending :  [7 6 5 4 3 2 1 0]


## Shape and Size

In [12]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([1., 1., 1., 1., 1., 1.])

`.ndim` memberi tahu jumlah axes, atau dimensi dari array

In [13]:
arr.ndim

2

`.size` : jumlah total elemen array.

In [14]:
arr.size

12

`.shape`: menampilkan tuple integer yg menunjukkan jumlah elemen yang disimpan di setiap dimensi array. contoh 2 row dan 3 col, maka menjadi (2,3)

In [15]:
arr.shape

(3, 4)

## Reshape

beberapa parameter: 
`numpy.reshape(a, newshape,order)`

In [17]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7])

In [37]:
print()
print("before:\n",ar, "\nshape: ")
print("after:\n", ar.reshape(4,2))



before:
 [0 1 2 3 4 5 6 7] 
shape: 
after:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]


## Convert 1D to 2D
- np.newaxis

In [38]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7])

In [63]:
ar.shape

(8,)

In [42]:
ar2 = ar[np.newaxis,:]
ar2

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [49]:
print(ar.ndim,"\n",
ar2.ndim)

1 
 2


In [50]:
ar2.shape

(1, 8)

- np.expand_dims

In [53]:
arr

(3, 4)

In [54]:
arr.shape

(3, 4)

In [71]:
arr_ex = np.expand_dims(arr, axis=0)

In [72]:
arr_ex

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [73]:
arr_ex.shape

(1, 3, 4)

In [74]:
arr_ex[np.newaxis, :].shape

(1, 1, 3, 4)

### Indexing and Slicing
    arr[start:stop:step]

In [77]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7])

In [80]:
ar[4:]

array([4, 5, 6, 7])

In [85]:
ar[2:8:2]

array([2, 4, 6])

In [87]:
ar > 2   

array([False, False, False,  True,  True,  True,  True,  True])

In [88]:
ar[ar>2]

array([3, 4, 5, 6, 7])

In [89]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [93]:
arr>5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [94]:
arr%2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [95]:
arr[arr%3 == 0]

array([ 3,  6,  9, 12])

In [96]:
(arr % 2 == 0) & (arr % 3 == 0)

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False,  True]])

In [97]:
arr[(arr % 2 == 0) & (arr % 3 == 0)]

array([ 6, 12])

## Creating from Existing Data

- slicing array 

In [101]:
ar1 = ar[3:8]
ar1

array([3, 4, 5, 6, 7])

- np.vstack() : menumpuk dua array yang ada secara vertikal

In [102]:
a_1 = np.array([[1, 1], [2, 2]])
print(a_1.shape)
a_1

(2, 2)


array([[1, 1],
       [2, 2]])

In [103]:
a_2 = np.array([[3, 3], [4, 4]])
print(a_2.shape)
a_2

(2, 2)


array([[3, 3],
       [4, 4]])

In [104]:
np.vstack([a_1, a_2])

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

- np.hstack() : menumpuk secara horizontal

In [106]:
np.hstack([a_1, a_2])

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

- np.hsplit() : Memecah/membagi secara horizontal

In [107]:
arrsplit = np.array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
    [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])
arrsplit

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [112]:
np.hsplit(arrsplit, 6)

[array([[ 1,  2],
        [13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8],
        [19, 20]]),
 array([[ 9, 10],
        [21, 22]]),
 array([[11, 12],
        [23, 24]])]

- np.vsplit() : Memecah/membagi secara vertikal


In [138]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [117]:
np.vsplit(arr,3)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

- .view dan .copy

In [143]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 7, 10, 11, 12],
       [13, 14, 15, 16]])

In [144]:
arr_2 = arr

In [145]:
print(id(arr))
print(id(arr_2))
print(id(arr) == id(arr_2))

140446137273104
140446137273104
True


Dalam kondisi `arr_2 = arr` di atas, arr dan arr_2 memiliki konektivitas sehingga ketika arr berubah maka arr_2 juga berubah

In [154]:
arr[2,0] = 7
arr_2[3,0] = 9
print(arr)
print(arr_2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 7 10 11 12]
 [ 9 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 7 10 11 12]
 [ 9 14 15 16]]


Untuk mengatasi permasalahan tersebut, kita bisa menggunakan `.view()` atau `.copy()`
- `.view()` : shallow copy, id berbeda tetapi kedua array masih bisa sama
- `.copy()` : deep copy

In [159]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 7, 10, 11, 12],
       [ 9, 14, 15, 16]])

In [161]:
arr_v = arr.view()
arr_v

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 9, 14, 15, 16]])

In [172]:
print(id(arr))
print(id(arr_v))
print(id(arr) == id(arr_v))

140446137273104
140446137274448
False


In [173]:
arr[2,0] = 150
print(arr)
print(arr_v)

[[  1   2   3   4]
 [  5   6   7   8]
 [150  10  11  12]
 [  9  14  15  16]]
[[  1   2   3   4]
 [  5   6   7   8]
 [150  10  11  12]
 [  9  14  15  16]]


In [174]:
arr_c = arr.copy()

In [175]:
print(id(arr))
print(id(arr_c))
print(id(arr) == id(arr_c))

140446137273104
140446142243312
False


In [176]:
arr[2,0] = 100
print(arr)
print(arr_c)

[[  1   2   3   4]
 [  5   6   7   8]
 [100  10  11  12]
 [  9  14  15  16]]
[[  1   2   3   4]
 [  5   6   7   8]
 [150  10  11  12]
 [  9  14  15  16]]


## Basic array operations

`addition, subtraction, multiplication, division, etc`

In [183]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7])

In [185]:
ar + 1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [187]:
ar * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35])

In [188]:
[1, 2, 3] * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [189]:
[1, 2, 3] + [5]

[1, 2, 3, 5]

In [191]:
ar + np.array([5])

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [192]:
ar/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5])

In [195]:
data = np.array([1, 2])
data

array([1, 2])

In [196]:
ones = np.ones(2)
ones

array([1., 1.])

In [197]:
data + ones

array([2., 3.])

In [198]:
data * ones

array([1., 2.])

In [199]:
data @ ones

3.0

## Broadcasting

In [200]:
data

array([1, 2])

In [201]:
data * 1.6

array([1.6, 3.2])

In [202]:
data + 2

array([3, 4])

## Array Operations

numpy bisa melakukan perhitungan lebih cepat

In [203]:
%%timeit
sum([1, 2, 3, 4])

82.9 ns ± 0.917 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [204]:
%%timeit
np.arange(1, 5).sum()

1.51 µs ± 31.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [205]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7])

In [207]:
print(ar.sum())
print(ar.max())
print(ar.min())

28
7
0


## Matrices
#### Creating Matrices

In [208]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [209]:
np.random.random((3, 2))

array([[0.29220594, 0.70477654],
       [0.762324  , 0.40295158],
       [0.64454557, 0.98251759]])

#### Matrix Arithmetic

In [210]:
data = np.arange(1, 5).reshape(2, 2)
ones = np.ones((2, 2))
ones_row = np.ones((1, 2))

print(data)
print(ones)
print(ones_row)

[[1 2]
 [3 4]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]]


In [211]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [212]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


#### Dot Product

In [213]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [214]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [215]:
np.dot(a_2, a_1)

array([[ 39,  54,  69],
       [ 49,  68,  87],
       [ 59,  82, 105]])

#### Matrix Indexing

In [220]:
a = arr
a

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [100,  10,  11,  12],
       [  9,  14,  15,  16]])

In [221]:
a[1][2]

7

In [223]:
a[2][-2] 

11

In [228]:
a[-1][-2] 

15

In [243]:
data = np.array([[1, 2, 5, 7], 
                 [3, 4, 7, 9], 
                 [5, 6, 9, 11]])

print(data)
# print(data[0])
# print(data[1])
# print(data[2])
print(data[0,1])
print(data[0:2])
print(data[0:2,2])



[[ 1  2  5  7]
 [ 3  4  7  9]
 [ 5  6  9 11]]
2
[[1 2 5 7]
 [3 4 7 9]]
[5 7]


### Matrix Aggregation

In [244]:
data

array([[ 1,  2,  5,  7],
       [ 3,  4,  7,  9],
       [ 5,  6,  9, 11]])

In [245]:
print(data.max())
print(data.min())
print(data.sum())

11
1
69


In [246]:
print(data.max(axis=0))
print(data.max(axis=1))

[ 5  6  9 11]
[ 7  9 11]


In [247]:
print(data.sum(axis=0))
print(data.sum(axis=1))

[ 9 12 21 27]
[15 23 31]


### Transposing & Reshaping

In [248]:
data

array([[ 1,  2,  5,  7],
       [ 3,  4,  7,  9],
       [ 5,  6,  9, 11]])

In [249]:
data.transpose()

array([[ 1,  3,  5],
       [ 2,  4,  6],
       [ 5,  7,  9],
       [ 7,  9, 11]])

In [250]:
data.T

array([[ 1,  3,  5],
       [ 2,  4,  6],
       [ 5,  7,  9],
       [ 7,  9, 11]])

In [251]:
data.shape

(3, 4)

In [253]:
data.reshape((6,2))

array([[ 1,  2],
       [ 5,  7],
       [ 3,  4],
       [ 7,  9],
       [ 5,  6],
       [ 9, 11]])

In [255]:
np.arange(15).reshape((5, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [261]:
np.linspace(0, 50, num=5)

array([ 0. , 12.5, 25. , 37.5, 50. ])

### N Dimensional Array

In [263]:
ndarr = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [264]:
ndarr.shape

(2, 2, 2)

In [265]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

### Flatten N-Dimensional Array

In [266]:
randomarr = np.random.random((4, 3, 2))
randomarr

array([[[0.73070679, 0.3138828 ],
        [0.2425171 , 0.66530517],
        [0.87096978, 0.19580857]],

       [[0.54045286, 0.71439925],
        [0.0877923 , 0.339858  ],
        [0.98148699, 0.28816523]],

       [[0.40178217, 0.44061897],
        [0.30686424, 0.10382329],
        [0.61541956, 0.69829346]],

       [[0.54635739, 0.07163962],
        [0.85074771, 0.35675899],
        [0.31738054, 0.89655865]]])

In [273]:
randomarr.flatten()

array([0.73070679, 0.3138828 , 0.2425171 , 0.66530517, 0.87096978,
       0.19580857, 0.54045286, 0.71439925, 0.0877923 , 0.339858  ,
       0.98148699, 0.28816523, 0.40178217, 0.44061897, 0.30686424,
       0.10382329, 0.61541956, 0.69829346, 0.54635739, 0.07163962,
       0.85074771, 0.35675899, 0.31738054, 0.89655865])

In [274]:
randomarr.reshape(-1)

array([0.73070679, 0.3138828 , 0.2425171 , 0.66530517, 0.87096978,
       0.19580857, 0.54045286, 0.71439925, 0.0877923 , 0.339858  ,
       0.98148699, 0.28816523, 0.40178217, 0.44061897, 0.30686424,
       0.10382329, 0.61541956, 0.69829346, 0.54635739, 0.07163962,
       0.85074771, 0.35675899, 0.31738054, 0.89655865])

In [275]:
randomarr.reshape(24,)

array([0.73070679, 0.3138828 , 0.2425171 , 0.66530517, 0.87096978,
       0.19580857, 0.54045286, 0.71439925, 0.0877923 , 0.339858  ,
       0.98148699, 0.28816523, 0.40178217, 0.44061897, 0.30686424,
       0.10382329, 0.61541956, 0.69829346, 0.54635739, 0.07163962,
       0.85074771, 0.35675899, 0.31738054, 0.89655865])

## Math Formulas

In [277]:
# error = (1/n) * np.sum(np.square(observed - prediction))